<a href="https://colab.research.google.com/github/DAJananiTK/IT-Service-Desk-Analytics-using-Python/blob/main/Python_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IT Service Management Analytics Using Python**

**Objectives**



1.   To analyze the overall distribution and trends of IT service desk support tickets.
2.   To evaluate ticket response and resolution performance across different priority levels and ticket statuses.

1.   To identify the most common ticket categories, affected services, and support channels.

1.   To assess the performance and workload distribution of IT support agents.
2. To examine the impact of SLA breaches, escalations, and outages on service desk operations.


2.  To derive meaningful insights that support data-driven decision-making for improving IT service management.

**Dataset** **Information**

Source : Mindweave Technologies. Help Desk Tickets (Synthetic) dataset, available through Hugging Face Datasets.

Location : Global (Synthetic Dataset – Not Associated with a Specific Country or Region)

Year/Timeline : Data collected during the period 2024 to 2025

Domain: Information Technology (IT)

**Stage** **1**

**1.1** **Business** **Problem**

Organizations rely on IT service desks to resolve technical issues quickly and maintain uninterrupted business operations. However, managing a large volume of support tickets across different departments, priorities, and services can be challenging. Delays in response and resolution, SLA breaches, ticket escalations, and uneven workload distribution among support agents can negatively impact employee productivity and service quality.This project aims to analyze IT service desk ticket data to identify operational bottlenecks, evaluate support performance, and uncover trends in ticket management. The insights generated will help improve response efficiency, optimize resource allocation, reduce SLA violations, and support data-driven decision-making for enhancing overall IT service management.

**1.2 Expected Outcome**



1.  Gain insights into IT service desk performance and ticket trends.
2.  Identify factors affecting response time, resolution time, and SLA compliance.

1.   Evaluate support agent performance and workload distribution.
2.  Discover high-demand ticket categories, services, and departments.

1.   Provide data-driven recommendations to improve IT service efficiency and support operations.
2.  Enable better decision-making through meaningful analysis and visualizations.

**1.3 Source, Size and Features**


**Source:**
* **Dataset Provider:** Mindweave Technologies
* **Platform:** Hugging Face
* **Dataset Name:** Help Desk Tickets (Synthetic)


**Size:**
* **10,000 IT service desk support tickets**
* **18 months of historical data**
* **5 related CSV tables** (Tickets, Categories, Agents, Comments, and SLA Breaches)


**Features:**
* Ticket ID
* Created Date & Time
* First Response Time
* Resolution Time
* Priority
* Status
* Support Channel
* Category
* Assigned Agent
* Requester Department
* Affected Service
* Ticket Summary & Description
* Escalation Status
* Outage Status
* SLA Breach Information
* Agent Details
* Category & Service Details
* Ticket Comments

**1.4** **Import libraries, load dataset**

In [ ]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [ ]:
# Load datasets from GitHub

tickets = pd.read_csv("https://raw.githubusercontent.com/DAJananiTK/IT-Service-Desk-Analytics-using-Python/refs/heads/main/tickets.csv")

agents = pd.read_csv("https://raw.githubusercontent.com/DAJananiTK/IT-Service-Desk-Analytics-using-Python/refs/heads/main/agents.csv")

categories = pd.read_csv("https://raw.githubusercontent.com/DAJananiTK/IT-Service-Desk-Analytics-using-Python/refs/heads/main/categories.csv")

comments = pd.read_csv("https://raw.githubusercontent.com/DAJananiTK/IT-Service-Desk-Analytics-using-Python/refs/heads/main/comments.csv")

sla_breaches = pd.read_csv("https://raw.githubusercontent.com/DAJananiTK/IT-Service-Desk-Analytics-using-Python/refs/heads/main/sla_breaches.csv")

**1.5 Dataset description (rows, columns, features)**

tickets.csv is the  main dataset thus included the  attribute table only for tickets.csv.The other CSV files (agents, categories, comments, and sla_breaches) are supporting tables.

| **Attribute Name**     | **Data Type** | **Description**                                                                   |
| ---------------------- | ------------- | --------------------------------------------------------------------------------- |
| `ticket_id`            | Integer       | Unique identifier for each support ticket.                                        |
| `created_at`           | DateTime      | Date and time when the ticket was created.                                        |
| `first_response_at`    | Time          | Time taken to provide the first response to the ticket.                           |
| `resolved_at`          | Time          | Time taken to resolve the ticket.                                                 |
| `priority`             | Categorical   | Priority level of the ticket (P1, P2, P3, P4).                                    |
| `status`               | Categorical   | Current status of the ticket (Resolved, Pending, Closed, etc.).                   |
| `channel`              | Categorical   | Support channel through which the ticket was raised (Email, Chat, Phone, Portal). |
| `category_id`          | Integer       | Unique identifier for the ticket category.                                        |
| `assigned_agent_id`    | Integer       | Unique identifier of the assigned support agent.                                  |
| `requester_department` | Categorical   | Department that submitted the support request.                                    |
| `affected_service`     | Categorical   | IT service impacted by the issue.                                                 |
| `summary`              | Text/String   | Brief summary of the reported issue.                                              |
| `description`          | Text/String   | Detailed description of the reported issue.                                       |
| `escalated`            | Boolean       | Indicates whether the ticket was escalated (`TRUE`/`FALSE`).                      |
| `outage_related`       | Boolean       | Indicates whether the ticket is related to a service outage (`TRUE`/`FALSE`).     |

**1.6 Initial EDA (head, info, describe, shape, null checks, duplicate check)**

In [ ]:
# head-view the first 5 rows
print("Tickets")
display(tickets.head())

print("Agents")
display(agents.head())

print("Categories")
display(categories.head())

print("Comments")
display(comments.head())

print("SLA Breaches")
display(sla_breaches.head())

Tickets

,ticket_id,created_at,first_response_at,resolved_at,priority,status,channel,category_id,assigned_agent_id,requester_department,affected_service,summary,description,escalated,outage_related
0,1,2024-01-01 00:25:58,2024-01-01 02:44:28.165882055,2024-01-01 07:11:36.270497762,P2,resolved,email,5,8,Finance,business-apps,New Zebra printer not visible to shipping stat...,New Zebra printer not visible to shipping stat...,False,False
1,2,2024-01-01 03:18:47,2024-01-01 10:41:36.758167460,2024-01-01 16:06:15.515350209,P3,resolved,email,8,5,Warehouse,voice,Sales laptop webcam missing from device manager.,Sales laptop webcam missing from device manage...,False,False
2,3,2024-01-01 05:00:04,2024-01-01 07:14:00.495197408,2024-01-03 05:17:17.430912834,P4,resolved,chat,4,2,IT,saas,Outlook keeps prompting for password on Mac.,Outlook keeps prompting for password on Mac. R...,False,False
3,4,2024-01-01 06:54:27,2024-01-01 13:53:34.348455884,2024-01-02 01:21:58.211483652,P3,resolved,portal,7,10,IT,security,VPN disconnects every 15 minutes on hotel Wi-Fi.,VPN disconnects every 15 minutes on hotel Wi-F...,False,False
4,5,2024-01-01 07:51:13,2024-01-01 09:57:48.722425448,2024-01-02 00:47:37.929284761,P3,resolved,chat,3,2,Finance,network,Spam burst hit shared support inbox this morning.,Spam burst hit shared support inbox this morni...,False,False

Agents

   id            name    team
0   1      Maya Patel  tier-1
1   2      Jordan Kim  tier-1
2   3  Avery Thompson  tier-1
3   4    Lucas Nguyen  tier-2
4   5   Sofia Ramirez  tier-2

Categories

   id                   name        service
0   1      Access Management       identity
1   2      Laptop / Endpoint       endpoint
2   3          Network & VPN        network
3   4  Email & Collaboration           saas
4   5              ERP / WMS  business-apps

Comments

,comment_id,ticket_id,agent_id,created_at,visibility,team,body
0,1,1,8,2024-01-01 07:51:48.512407,public,business-apps,Issue now limited to users on macOS Sonoma.
1,2,1,8,2024-01-01 15:37:09.392051,public,business-apps,Issue now limited to users on macOS Sonoma.
2,3,1,8,2024-01-02 01:44:23.067300,internal,business-apps,Confirmed issue reproducible on spare device.
3,4,1,8,2024-01-02 19:26:32.801904,public,business-apps,MFA re-registration completed successfully.
4,5,2,5,2024-01-01 14:31:12.901622,public,tier-2,Monitor issue persisted after cable swap.

SLA Breaches

,breach_id,ticket_id,breach_type,sla_target_hours,actual_hours,breach_minutes
0,1,11,resolution,24,28.51,270
1,2,13,resolution,72,75.94,236
2,3,15,resolution,72,74.87,172
3,4,20,resolution,72,76.87,292
4,5,21,resolution,72,74.25,134

In [ ]:
# info- checks the dataset information
tickets.info()

agents.info()

categories.info()

comments.info()

sla_breaches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ticket_id             1000 non-null   int64
 1   created_at            1000 non-null   object
 2   first_response_at     1000 non-null   object
 3   resolved_at           899 non-null    object
 4   priority              1000 non-null   object
 5   status                1000 non-null   object
 6   channel               1000 non-null   object
 7   category_id           1000 non-null   int64
 8   assigned_agent_id     1000 non-null   int64
 9   requester_department  1000 non-null   object
 10  affected_service      1000 non-null   object
 11  summary               1000 non-null   object
 12  description           1000 non-null   object
 13  escalated             1000 non-null   bool
 14  outage_related        1000 non-null   bool
dtypes: bool(2), int64(3), object(10)
memory usage: 103.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   name    10 non-null     object
 2   team    10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       8 non-null      int64
 1   name     8 non-null      object
 2   service  8 non-null      object
dtypes: int64(1), object(2)
memory usage: 324.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   comment_id  2000 non-null   int64
 1   ticket_id   2000 non-null   int64
 2   agent_id    2000 non-null   int64
 3   created_at  2000 non-null   object
 4   visibility  2000 non-null   object
 5   team        2000 non-null   object
 6   body        2000 non-null   object
dtypes: int64(3), object(4)
memory usage: 109.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1249 entries, 0 to 1248
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   breach_id         1249 non-null   int64
 1   ticket_id         1249 non-null   int64
 2   breach_type       1249 non-null   object
 3   sla_target_hours  1249 non-null   int64
 4   actual_hours      1249 non-null   float64
 5   breach_minutes    1249 non-null   int64
dtypes: float64(1), int64(4), object(1)
memory usage: 58.7+ KB

In [ ]:
# describe- view the statistical summary of tables having numeric columns
tickets.describe()

         ticket_id  category_id  assigned_agent_id
count  1000.000000  1000.000000         1000.00000
mean    500.500000     4.454000            5.53700
std     288.819436     2.308942            2.88287
min       1.000000     1.000000            1.00000
25%     250.750000     2.000000            3.00000
50%     500.500000     4.000000            6.00000
75%     750.250000     6.250000            8.00000
max    1000.000000     8.000000           10.00000

In [ ]:
# shape- checks the shape
print("Tickets:", tickets.shape)
print("Agents:", agents.shape)
print("Categories:", categories.shape)
print("Comments:", comments.shape)
print("SLA Breaches:", sla_breaches.shape)

Tickets: (1000, 15)
Agents: (10, 3)
Categories: (8, 3)
Comments: (2000, 7)
SLA Breaches: (1249, 6)

In [ ]:
# isnull()- checks the missing values
print(tickets.isnull().sum())

print(agents.isnull().sum())

print(categories.isnull().sum())

print(comments.isnull().sum())

print(sla_breaches.isnull().sum())

ticket_id                 0
created_at                0
first_response_at         0
resolved_at             101
priority                  0
status                    0
channel                   0
category_id               0
assigned_agent_id         0
requester_department      0
affected_service          0
summary                   0
description               0
escalated                 0
outage_related            0
dtype: int64
id      0
name    0
team    0
dtype: int64
id         0
name       0
service    0
dtype: int64
comment_id    0
ticket_id     0
agent_id      0
created_at    0
visibility    0
team          0
body          0
dtype: int64
breach_id           0
ticket_id           0
breach_type         0
sla_target_hours    0
actual_hours        0
breach_minutes      0
dtype: int64

In [ ]:
# duplicated()-checks the duplicate records
print("Tickets:", tickets.duplicated().sum())

print("Agents:", agents.duplicated().sum())

print("Categories:", categories.duplicated().sum())

print("Comments:", comments.duplicated().sum())

print("SLA Breaches:", sla_breaches.duplicated().sum())

Tickets: 0
Agents: 0
Categories: 0
Comments: 0
SLA Breaches: 0